// This file is auto-generated by @hey-api/openapi-ts

export type GetAllProjectsForUserV1Data = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/projects';
};

export type GetAllProjectsForUserV1Responses = {
    200: unknown;
};

export type CreateProjectV1Data = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/projects';
};

export type CreateProjectV1Responses = {
    201: unknown;
};

export type DeleteProjectV1Data = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/projects/{projectId}';
};

export type DeleteProjectV1Responses = {
    200: unknown;
};

export type GetProjectByIdV1Data = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/projects/{projectId}';
};

export type GetProjectByIdV1Responses = {
    200: unknown;
};

export type CreateUserV1Data = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/users/register';
};

export type CreateUserV1Responses = {
    201: unknown;
};

export type LoginV1Data = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/users/login';
};

export type LoginV1Responses = {
    201: unknown;
};

export type CreateTaskV1Data = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/tasks';
};

export type CreateTaskV1Responses = {
    201: unknown;
};

export type DeleteTaskV1Data = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/tasks/{taskId}';
};

export type DeleteTaskV1Responses = {
    200: unknown;
};

export type UpdateTaskV1Data = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/tasks/{taskId}';
};

export type UpdateTaskV1Responses = {
    200: unknown;
};

export type ClientOptions = {
    baseUrl: string;
};